# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-05 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_auto_20170602_0725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posting',
            name='create_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='posting',
            name='modified_date',
            field=models.DateTimeField(),
        ),
    ]
